// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(width, height) {
    var canvas;
    canvas = document.createElement("canvas");
    if (canvas == null) {
      return null;
    }
    canvas.width = width;
    canvas.height = height;
    return canvas;
  };

}).call(this);
