// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(width, height) {
    var canvas, ctx;
    canvas = document.createElement("canvas");
    if ((canvas != null ? canvas.getContext : void 0) == null) {
      return {};
    }
    ctx = canvas.getContext("2d");
    canvas.width = width;
    canvas.height = height;
    return {
      canvas: canvas,
      ctx: ctx
    };
  };

}).call(this);
